#!/bin/bash

#======================================================================
# Creates or updates .mo files
#
# USAGE:
#   make-mo [lang]
#
# NAME:
#   MO-file maker
#
# REQUIREMENTS:
#   msgfmt
#
# AUTHOR:
#   Aleksey Nemiro
#   http://aleksey.nemiro.ru/
#   https://github.com/alekseynemiro/
#   <aleksey@nemiro.ru>
#   <aleksey.nemiro@gmail.com>
#
# VERSION:
#   1.0
#
# CREATED:
#   14.01.2016
#
# REVISION:
#   14.01.2016
#
# COPYRIGHT:
#   © Aleksey Nemiro, 2016. All rights reserved.
#
# LICENSE:
#   Apache License Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0
#======================================================================

lang="$1"
path="$(cd "$(dirname "$0")" && pwd)"

if [[ -n "$lang" ]]; then
  path="$path/$lang"
  if [[ ! -d "$path" ]]; then
    mkdir "$path"
  fi
fi

cd "$path"

find "$path" -name "*.po" | while read -r f; do
  po_dir="$(dirname $f)"
  po_file="$(basename $f)"
  po_name="$(echo $po_file | cut -d'.' -f1)"
  msgfmt --output-file="$po_dir/$po_name.mo" "$f" && \
  printf "Created: $po_dir/$po_name.mo\n" || \
  printf "ERROR: Could not create mo-file from: $f\n"
done