#!/bin/bash

#======================================================================
# Performs installation and configuration of etckeeper.
#
# USAGE:
#   etckeeper [--debug] [--version] [--help] [--nocolor] [--tested]
#
# PROJECT:
#   Hosting tools by Aleksey Nemiro (HTAN)
#
# REQUIREMENTS:
#   Debian 7/8, sudo
#
# AUTHOR:
#   Aleksey Nemiro
#   http://aleksey.nemiro.ru/
#   https://github.com/alekseynemiro/
#   <aleksey@nemiro.ru>
#   <aleksey.nemiro@gmail.com>
#
# VERSION:
#   1.0.0
#
# CREATED:
#   26.11.2015
#
# REVISION:
#   25.05.2016
#
# COPYRIGHT:
#   © Aleksey Nemiro, 2015-2016. All rights reserved.
#
# LICENSE:
#   Apache License Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0
#
# HTAN_NAME:
#   Etckeeper - monitor changes to /etc with git
#
# HTAN_CATEGORY:
#   Tools
#
# HTAN_OPTIONAL:
#   true
#======================================================================

# Including common
if [[ -z "$HTAN_INCLUDED_TOOLS" ]]; then
  {
    if [[ "${0##*/}" != "etckeeper" ]]; then
      printf "Including the common …"
    fi
    if source "$(cd $(dirname $0) && pwd)/../tools/common"; then
      if [[ "${0##*/}" != "etckeeper" ]]; then
        OK
      fi
    fi
  } || {
    echo ""
    echo -e "\033[1;31m$(gettext "Failed to include the common.")\033[0m"
    exit 1
  }
fi

# Including tools
IncludeTool package service

InstallEtckeeper()
{
  # tested version
  local tested
  if [[ "$HTAN_TESTED" == true ]]; then
    tested="-version=1.15"
  fi
  # // --

  if ! $HTAN_NOHEADERS; then
    Line =
    Message "$(gettext "# Installing and configuring %s.")" "Etckeeper" -s="$DEF_STYLE_HEADER"
    Line =

    Message "$(gettext "Etckeeper lets you keep /etc under version control.")"
    Line
  fi

  if ! PackageInstall "etckeeper" -confirm="$(NeedUserConfirmationToInstall true)" $tested; then
    Line
    Message "$(gettext "%s has not been installed.")" "Etckeeper"
    return
  fi

  Line

  if [[ ! -f "$HTAN_PATH_DATA/etckeeper.conf" ]]; then
    Message "$(gettext "File %s was not found.")" "$HTAN_PATH_DATA/etckeeper.conf" -s="$DEF_STYLE_ERROR"
    return 1
  fi

  PackageInstall "git" -confirm=false

  Line

  local c="sudo cp $HTAN_PATH_DATA/etckeeper.conf /etc/etckeeper/etckeeper.conf >> $HTAN_LOG 2>&1"

  Execute -c="$c" -m="$(gettext "Configuring %s …")" -a="etckeeper" -sp="$DEF_STYLE_ACTION_PROC" -sc="$DEF_STYLE_ACTION_COMP"

  if [[ ! -d "/etc/.git" ]]; then
    Line
    c="sudo bash -c 'cd /etc; "
    c+="etckeeper init >> $HTAN_LOG 2>&1; "
    c+="etckeeper commit \"Initial commit\" >> $HTAN_LOG 2>&1'"
    Execute -c="$c" -m="Initial commit …" -sp="$DEF_STYLE_ACTION_PROC" -sc="$DEF_STYLE_ACTION_COMP"
  fi

  Line
  Message "$(gettext "Done.")"
}

InstallEtckeeper