#!/bin/bash

#======================================================================
# Performs installation and configuration of fail2ban.
#
# USAGE:
#   fail2ban [--debug] [--version] [--help] [--nocolor] [--tested]
#
# PROJECT:
#   Hosting tools by Aleksey Nemiro (HTAN)
#
# REQUIREMENTS:
#   Debian 8, sudo, HTAN Tools
#
# AUTHOR:
#   Aleksey Nemiro
#   http://aleksey.nemiro.ru/
#   https://github.com/alekseynemiro/
#   <aleksey@nemiro.ru>
#   <aleksey.nemiro@gmail.com>
#
# VERSION:
#   1.0.1
#
# CREATED:
#   21.11.2015
#
# REVISION:
#   19.04.2016
#
# COPYRIGHT:
#   © Aleksey Nemiro, 2015-2016. All rights reserved.
#
# LICENSE:
#   Apache License Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0
#
# HTAN_NAME:
#   Fail2ban - protection against network attacks
#
# HTAN_CATEGORY:
#   Security
#
# HTAN_OPTIONAL:
#   true
#======================================================================

# Including common
if [[ -z "$HTAN_INCLUDED_TOOLS" ]]; then
  {
    if [[ "${0##*/}" != "fail2ban" ]]; then
      printf "Including the common …"
    fi
    if source "$(cd $(dirname $0) && pwd)/../tools/common"; then
      if [[ "${0##*/}" != "fail2ban" ]]; then
        OK
      fi
    fi
  } || {
    echo ""
    echo -e "\033[1;31m$(gettext "Failed to include the common.")\033[0m"
    exit 1
  }
fi

# Including tools
IncludeTool package service config

InstallFail2Ban()
{
  # tested version
  local tested
  if [[ "$HTAN_TESTED" == true ]]; then
    tested="-version=0.8.13"
  fi
  # // --

  Line =
  Message "$(gettext "# Installing and configuring %s.")" "Fail2ban" -s="$DEF_STYLE_HEADER"
  Line =

  # Fail2ban - программа для защиты сервера от различного вида атак.
  Message "$(gettext "Fail2ban is an intrusion prevention software framework which protects computer servers from brute-force attacks.")"
  Line

  if ! PackageInstall "fail2ban" -confirm=true $tested; then
    Message "$(gettext "%s has not been installed.")" "Fail2ban"
    return
  fi

  # ServiceStop fail2ban

  local config=/etc/fail2ban/jail.conf

  # DEFAULT
  INI_SetValue "$config" -section="DEFAULT" -key="bantime" -value="600"
  INI_SetValue "$config" -section="DEFAULT" -key="ignoreip" -value="127.0.0.1/8"
  INI_SetValue "$config" -section="DEFAULT" -key="findtime" -value="600"
  INI_SetValue "$config" -section="DEFAULT" -key="maxretry" -value="10"

  # INI_SetValue "$config" -section="DEFAULT" -key="destemail" -value="root@localhost"
  # INI_SetValue "$config" -section="DEFAULT" -key="sendername" -value="Fail2Ban"
  # INI_SetValue "$config" -section="DEFAULT" -key="sender" -value="fail2ban@localhost"
  # INI_SetValue "$config" -section="DEFAULT" -key="mta" -value="sendmail"
  # INI_SetValue "$config" -section="DEFAULT" -key="protocol" -value="tcp"

  # ssh
  INI_SetValue "$config" -section="ssh" -key="enabled" -value="true"
  INI_SetValue "$config" -section="ssh" -key="port" -value="ssh"
  INI_SetValue "$config" -section="ssh" -key="filter" -value="sshd"
  INI_SetValue "$config" -section="ssh" -key="logpath" -value="/var/log/auth.log"
  INI_SetValue "$config" -section="ssh" -key="maxretry" -value="10"

  # vsftpd
  if PackageExists vsftpd; then
    INI_SetValue "$config" -section="vsftpd" -key="enabled" -value="true"
    INI_SetValue "$config" -section="vsftpd" -key="port" -value="ftp,ftp-data,ftps,ftps-data"
    INI_SetValue "$config" -section="vsftpd" -key="filter" -value="vsftpd"
    INI_SetValue "$config" -section="vsftpd" -key="logpath" -value="/var/log/vsftpd.log"
    INI_SetValue "$config" -section="vsftpd" -key="maxretry" -value="10"
  fi

  # postfix
  if PackageExists postfix; then
    INI_SetValue "$config" -section="postfix" -key="enabled" -value="true"
    INI_SetValue "$config" -section="postfix" -key="port" -value="smtp,ssmtp,submission"
    INI_SetValue "$config" -section="postfix" -key="filter" -value="postfix"
    INI_SetValue "$config" -section="postfix" -key="logpath" -value="/var/log/mail.log"
  fi

  # nginx-http-auth
  INI_SetValue "$config" -section="nginx-http-auth" -key="enabled" -value="true"
  INI_SetValue "$config" -section="nginx-http-auth" -key="port" -value="http,https"
  INI_SetValue "$config" -section="nginx-http-auth" -key="filter" -value="nginx-http-auth"
  INI_SetValue "$config" -section="nginx-http-auth" -key="logpath" -value="/var/log/nginx/error.log"
  INI_SetValue "$config" -section="nginx-http-auth" -key="maxretry" -value="10"

  # nginx-badbots
  # INI_SetValue "$config" -section="nginx-badbots" -key="enabled" -value="true"
  # INI_SetValue "$config" -section="nginx-badbots" -key="port" -value="http,https"
  # INI_SetValue "$config" -section="nginx-badbots" -key="filter" -value="nginx-badbots"
  # INI_SetValue "$config" -section="nginx-badbots" -key="logpath" -value="/var/log/nginx/access.log"
  # INI_SetValue "$config" -section="nginx-http-auth" -key="maxretry" -value="5"

  # mysql
  if PackageExists mysql-server; then
    INI_SetValue "$config" -section="mysqld-auth" -key="enabled" -value="true"
    INI_SetValue "$config" -section="mysqld-auth" -key="port" -value="3306"
    INI_SetValue "$config" -section="mysqld-auth" -key="filter" -value="mysqld-auth"
    INI_SetValue "$config" -section="mysqld-auth" -key="logpath" -value="/var/log/mysqld.log"
  fi

  ServiceRestart fail2ban

  Line
  Message "$(gettext "Done.")"
}

InstallFail2Ban