#!/bin/bash

#======================================================================
# Performs installation and configuration of fail2ban.
#
# USAGE:
#   fail2ban [--debug] [--version] [--help] [--nocolor] [--tested]
#
# PROJECT:
#   Hosting tools by Aleksey Nemiro (HTAN)
#
# REQUIREMENTS:
#   Debian 7/8, sudo
#
# AUTHOR:
#   Aleksey Nemiro
#   http://aleksey.nemiro.ru/
#   https://github.com/alekseynemiro/
#   <aleksey@nemiro.ru>
#   <aleksey.nemiro@gmail.com>
#
# VERSION:
#   1.0.2
#
# CREATED:
#   21.11.2015
#
# REVISION:
#   26.05.2016
#
# COPYRIGHT:
#   © Aleksey Nemiro, 2015-2016. All rights reserved.
#
# LICENSE:
#   Apache License Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0
#
# HTAN_NAME:
#   Fail2ban - protection against network attacks
#
# HTAN_CATEGORY:
#   Security
#
# HTAN_OPTIONAL:
#   true
#======================================================================

# Including common
if [[ -z "$HTAN_INCLUDED_TOOLS" ]]; then
  {
    if [[ "${0##*/}" != "fail2ban" ]]; then
      printf "Including the common …"
    fi
    if source "$(cd $(dirname $0) && pwd)/../tools/common"; then
      if [[ "${0##*/}" != "fail2ban" ]]; then
        OK
      fi
    fi
  } || {
    echo ""
    echo -e "\033[1;31m$(gettext "Failed to include the common.")\033[0m"
    exit 1
  }
fi

# Including tools
IncludeTool package service config

InstallFail2Ban()
{
  # tested version
  local tested
  if [[ "$HTAN_TESTED" == true ]]; then
    tested="-version=0.8.13"
  fi
  # // --

  if ! $HTAN_NOHEADERS; then
    Line =
    Message "$(gettext "# Installing and configuring %s.")" "Fail2ban" -s="$DEF_STYLE_HEADER"
    Line =

    Message "$(gettext "Fail2ban is an intrusion prevention software framework which protects computer servers from brute-force attacks.")"
    Line
  fi

  if ! PackageInstall "fail2ban" -confirm="$(NeedUserConfirmationToInstall true)" $tested; then
    Message "$(gettext "%s has not been installed.")" "Fail2ban"
    return
  fi

  # ServiceStop fail2ban

  local config=/etc/fail2ban/jail.conf

  # DEFAULT
  INI_SetValue "$config" -section="DEFAULT" -key="bantime" -value="600"
  INI_SetValue "$config" -section="DEFAULT" -key="ignoreip" -value="127.0.0.1/8"
  INI_SetValue "$config" -section="DEFAULT" -key="findtime" -value="600"
  INI_SetValue "$config" -section="DEFAULT" -key="maxretry" -value="10"

  # INI_SetValue "$config" -section="DEFAULT" -key="destemail" -value="root@localhost"
  # INI_SetValue "$config" -section="DEFAULT" -key="sendername" -value="Fail2Ban"
  # INI_SetValue "$config" -section="DEFAULT" -key="sender" -value="fail2ban@localhost"
  # INI_SetValue "$config" -section="DEFAULT" -key="mta" -value="sendmail"
  # INI_SetValue "$config" -section="DEFAULT" -key="protocol" -value="tcp"

  # ssh
  INI_SetValue "$config" -section="ssh" -key="enabled" -value="true"
  INI_SetValue "$config" -section="ssh" -key="port" -value="ssh"
  INI_SetValue "$config" -section="ssh" -key="filter" -value="sshd"
  INI_SetValue "$config" -section="ssh" -key="logpath" -value="/var/log/auth.log"
  INI_SetValue "$config" -section="ssh" -key="maxretry" -value="10"

  Fail2BanCheckFile "/var/log/auth.log"

  # vsftpd
  if PackageInstalled vsftpd; then
    INI_SetValue "$config" -section="vsftpd" -key="enabled" -value="true"
    INI_SetValue "$config" -section="vsftpd" -key="port" -value="ftp,ftp-data,ftps,ftps-data"
    INI_SetValue "$config" -section="vsftpd" -key="filter" -value="vsftpd"
    INI_SetValue "$config" -section="vsftpd" -key="logpath" -value="/var/log/vsftpd.log"
    INI_SetValue "$config" -section="vsftpd" -key="maxretry" -value="10"

    Fail2BanCheckFile "/var/log/vsftpd.log"
  fi

  # postfix
  if PackageInstalled postfix; then
    INI_SetValue "$config" -section="postfix" -key="enabled" -value="true"
    INI_SetValue "$config" -section="postfix" -key="port" -value="smtp,ssmtp,submission"
    INI_SetValue "$config" -section="postfix" -key="filter" -value="postfix"
    INI_SetValue "$config" -section="postfix" -key="logpath" -value="/var/log/mail.log"

    Fail2BanCheckFile "/var/log/mail.log"
  fi

  # nginx-http-auth
  INI_SetValue "$config" -section="nginx-http-auth" -key="enabled" -value="true"
  INI_SetValue "$config" -section="nginx-http-auth" -key="port" -value="http,https"
  INI_SetValue "$config" -section="nginx-http-auth" -key="filter" -value="nginx-http-auth"
  INI_SetValue "$config" -section="nginx-http-auth" -key="logpath" -value="/var/log/nginx/error.log"
  INI_SetValue "$config" -section="nginx-http-auth" -key="maxretry" -value="10"

  Fail2BanCheckFile "/var/log/nginx/error.log"

  # nginx-badbots
  # INI_SetValue "$config" -section="nginx-badbots" -key="enabled" -value="true"
  # INI_SetValue "$config" -section="nginx-badbots" -key="port" -value="http,https"
  # INI_SetValue "$config" -section="nginx-badbots" -key="filter" -value="nginx-badbots"
  # INI_SetValue "$config" -section="nginx-badbots" -key="logpath" -value="/var/log/nginx/access.log"
  # INI_SetValue "$config" -section="nginx-http-auth" -key="maxretry" -value="5"

  # mysql
  if PackageInstalled mysql-server; then
    INI_SetValue "$config" -section="mysqld-auth" -key="enabled" -value="true"
    INI_SetValue "$config" -section="mysqld-auth" -key="port" -value="3306"
    INI_SetValue "$config" -section="mysqld-auth" -key="filter" -value="mysqld-auth"
    INI_SetValue "$config" -section="mysqld-auth" -key="logpath" -value="/var/log/mysqld.log"

    Fail2BanCheckFile "/var/log/mysqld.log"
  fi

  ServiceRestart fail2ban

  # testing
  if [[ -f "/var/log/fail2ban.log" ]]; then
    Line
    Message "$(gettext "Testing for errors …")" -n -s="$DEF_STYLE_ACTION_COMP"
    if sudo grep -q 'ERROR' /var/log/fail2ban.log >> $HTAN_LOG 2>&1; then
      Fail
      Line
      sudo grep --color 'ERROR' /var/log/fail2ban.log
    else
      OK
    fi
  fi

  Line
  Message "$(gettext "Done.")"
}

Fail2BanCheckFile()
{
  local f2bcf_path="$1"
  if [[ ! -f "$f2bcf_path" ]]; then
    sudo touch "$f2bcf_path" >> $HTAN_LOG 2>&1
    Message "$(gettext "WARNING: File %s not found. This can cause problems in the fail2ban. HTAN create an empty file, but you need to make sure that everything works.")" "$f2bcf_path" -s="$DEF_STYLE_WAITING"
    Line
    sleep 3
  fi
}

InstallFail2Ban