#!/bin/bash

#======================================================================
# Performs installation and configuration of MySql.
#
# USAGE:
#   mysql [--debug] [--version] [--help] [--nocolor]
#
# PROJECT:
#   Hosting tools by Aleksey Nemiro (HTAN)
#
# REQUIREMENTS:
#   Debian 7/8 or Ubuntu 14+, sudo
#
# AUTHOR:
#   Aleksey Nemiro
#   http://aleksey.nemiro.ru/
#   https://github.com/alekseynemiro/
#   <aleksey@nemiro.ru>
#   <aleksey.nemiro@gmail.com>
#
# VERSION:
#   1.0.1
#
# CREATED:
#   23.09.2015
#
# REVISION:
#   28.05.2016
#
# COPYRIGHT:
#   © Aleksey Nemiro, 2015-2016. All rights reserved.
#
# LICENSE:
#   Apache License Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0
#
# HTAN_NAME:
#   MySql
#
# HTAN_CATEGORY:
#   Database
#
# HTAN_OPTIONAL:
#   true
#======================================================================

# Including common
if [[ -z "$HTAN_INCLUDED_TOOLS" ]]; then
  {
    if [[ "${0##*/}" != "mysql" ]]; then
      printf "Including the common …"
    fi
    if source "$(cd $(dirname $0) && pwd)/../tools/common"; then
      if [[ "${0##*/}" != "mysql" ]]; then
        OK
      fi
    fi
  } || {
    echo ""
    echo -e "\033[1;31m$(gettext "Failed to include the common.")\033[0m"
    exit 1
  }
fi

# Including tools
IncludeTool package service config

declare HTAN_MYSQL_HOST="localhost"
declare HTAN_MYSQL_PORT=3306
declare HTAN_MYSQL_ROOT_PASSWORD=""

InstallMySql()
{
  if ! $HTAN_NOHEADERS; then
    Line =
    Message "$(gettext "# Installing and configuring %s.")" "MySql" -s="$DEF_STYLE_HEADER"
    Line =

    Message "$(gettext "MySQL is an open-source relational database management system.")"

    Line
  fi

  if ! PackageInstall mysql-server -confirm="$(NeedUserConfirmationToInstall true)" -title="MySql"; then
    Line
    Message "$(gettext "Installation canceled by the user.")"
    return
  fi

  Line

  if ! EnterPassword -t="$(printf "$(gettext "Come up and enter the root password for %s:")" "MySql")" -w="$(printf "$(gettext "Without password %s is unsafe!")" "MySql")" -o; then
    Line
    Message "$(gettext "%s server was not configured correctly. Operation canceled by the user.")" "MySql"
    return
  fi

  HTAN_MYSQL_ROOT_PASSWORD="$HTAN_PASSWORD"

  Line

  local c="sudo mysqladmin -u root password $HTAN_MYSQL_ROOT_PASSWORD >> $HTAN_LOG 2>&1"

  Execute -c="$c" -m="$(gettext "Setting the root password for %s …")" -a="MySql" -sp="$DEF_STYLE_ACTION_PROC" -sc="$DEF_STYLE_ACTION_COMP"

  # /etc/mysql/my.cnf

  ServerInfo "$(gettext "MySql server"):\n"
  ServerInfo "--------------------------------------------\n"
  ServerInfo "$(gettext "Host"): $HTAN_MYSQL_HOST\n" # $HTAN_SERVER_IP
  ServerInfo "$(gettext "Port"): $HTAN_MYSQL_PORT\n"
  ServerInfo "$(gettext "Login"): root\n"
  ServerInfo "$(gettext "Password"): $HTAN_MYSQL_ROOT_PASSWORD\n"
  ServerInfo "--------------------------------------------\n\n"

  Line
  Message "$(gettext "Done.")"
}

InstallMySql