#!/bin/bash

#======================================================================
# Performs installation and configuration of PHP5.
#
# USAGE:
#   php5 [--debug] [--version] [--help] [--nocolor]
#
# PROJECT:
#   Hosting tools by Aleksey Nemiro (HTAN)
#
# REQUIREMENTS:
#   Debian 7/8, sudo
#
# AUTHOR:
#   Aleksey Nemiro
#   http://aleksey.nemiro.ru/
#   https://github.com/alekseynemiro/
#   <aleksey@nemiro.ru>
#   <aleksey.nemiro@gmail.com>
#
# VERSION:
#   1.0.1
#
# CREATED:
#   20.09.2015
#
# REVISION:
#   27.05.2016
#
# COPYRIGHT:
#   © Aleksey Nemiro, 2015-2016. All rights reserved.
#
# LICENSE:
#   Apache License Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0
#
# HTAN_NAME:
#   PHP5
#
# HTAN_CATEGORY:
#   Application Development
#
# HTAN_OPTIONAL:
#   true
#======================================================================

# Including common
if [[ -z "$HTAN_INCLUDED_TOOLS" ]]; then
  {
    if [[ "${0##*/}" != "php5" ]]; then
      printf "Including the common …"
    fi
    if source "$(cd $(dirname $0) && pwd)/../tools/common"; then
      if [[ "${0##*/}" != "php5" ]]; then
        OK
      fi
    fi
  } || {
    echo ""
    echo -e "\033[1;31m$(gettext "Failed to include the common.")\033[0m"
    exit 1
  }
fi

# Including tools
IncludeTool package service config

InstallPHP5()
{
  if ! $HTAN_NOHEADERS; then
    Line =
    Message "$(gettext "# Installing and configuring %s.")" "PHP5" -s="$DEF_STYLE_HEADER"
    Line =
  fi

  if [[ "$SYS_OS_NAME" == "Ubuntu" ]]; then
    Message "$(gettext "Not available for %s.")" "$SYS_OS_NAME" -s="$DEF_STYLE_ERROR"
    return 1
  fi

  if PackageInstalled "php7" || PackageInstalled "php7.0"; then
    Message "$(gettext "On this server is already installed %s.")" "PHP7"
    Message "$(gettext "Installation of %s is not possible.")." "PHP5"
    return
  fi

  if ! $HTAN_INSTALL_CONFIRMED; then
    if ! Confirm "$(gettext "Do you want to install %s?")" "PHP5" -yes; then
      Line
      Message "$(gettext "Installation canceled by the user.")"
      return
    else
      Line
    fi
  fi

  if PackageInstalled apache2; then
    PackageInstall "php5" -confirm=false -title="PHP5"
    Line
    PackageInstall libapache2-mod-php5 -confirm=false
    Line
  fi

  PackageInstall php5-fpm -confirm=false
  Line

  PackageInstall php5-cgi -confirm=false
  Line

  if Confirm "$(gettext "Do you want to install the Developer Tools for %s?")" "PHP5" -no; then
    Line
    PackageInstall "php5-dev" -confirm=false
  fi

  ServerInfo "PHP5:\n"
  ServerInfo "--------------------------------------------\n"
  ServerInfo "$(gettext "Location"): $phpPath\n"
  if PackageInstalled apache2; then
    ServerInfo "$(gettext "Config file"): /etc/php5/apache2/php.ini\n"
  fi
  ServerInfo "$(gettext "Config file"): /etc/php5/cli/php.ini\n"
  ServerInfo "$(gettext "Config file"): /etc/php5/fpm/php.ini\n"
  ServerInfo "$(gettext "Daemon name"): php5-fpm\n"
  ServerInfo "$(gettext "Socket"): /var/run/php5-fpm.sock\n"
  ServerInfo "--------------------------------------------\n\n"

  Line
  Message "$(gettext "Done.")"
}

InstallPHP5