#!/bin/bash

#======================================================================
# Performs installation and configuration of PHP5.
#
# USAGE:
#   php5 [--debug] [--version] [--help] [--nocolor] [--tested]
#
# PROJECT:
#   Hosting tools by Aleksey Nemiro (HTAN)
#
# REQUIREMENTS:
#   Debian 8, sudo, HTAN Tools
#
# AUTHOR:
#   Aleksey Nemiro
#   http://aleksey.nemiro.ru/
#   https://github.com/alekseynemiro/
#   <aleksey@nemiro.ru>
#   <aleksey.nemiro@gmail.com>
#
# VERSION:
#   1.0.0
#
# CREATED:
#   20.09.2015
#
# REVISION:
#   25.11.2015
#
# COPYRIGHT:
#   © Aleksey Nemiro, 2015. All rights reserved.
#
# LICENSE:
#   Apache License Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0
#
# HTAN_NAME:
#   PHP5
#
# HTAN_CATEGORY:
#   Application Development
#
# HTAN_OPTIONAL:
#   true
#======================================================================

# Including common
if [[ -z "$HTAN_INCLUDED_TOOLS" ]]; then
  {
    if [[ "${0##*/}" != "php5" ]]; then
      printf "Including the common …"
    fi
    if source "$(cd $(dirname $0) && pwd)/../tools/common"; then
      if [[ "${0##*/}" != "php5" ]]; then
        OK
      fi
    fi
  } || {
    echo ""
    echo -e "\033[1;31m$(gettext "Failed to include the common.")\033[0m"
    exit 1
  }
fi

# Including tools
IncludeTool package service config

InstallPHP5()
{
  # tested version
  local -A tested
  if [[ "$HTAN_TESTED" == true ]]; then
    tested[php5]="-version=5.6.14"
    tested[php5-dev]="-version=5.6.14"
    tested[libapache2-mod-php5]="-version=5.6.14"
    tested[php5-fpm]="-version=5.6.14"
  fi
  # // --

  Line =
  Message "$(gettext "# Installing and configuring %s.")" "PHP5" -s="$DEF_STYLE_HEADER"
  Line =

  if ! PackageInstall "php5" -confirm=true -title="PHP5" ${tested[php5]}; then
    Line
    return 0
  fi

  Line
  PackageInstall php5-fpm -confirm=false ${tested[php5-fpm]}

  Line

  PackageInstall libapache2-mod-php5 -confirm=false ${tested[libapache2-mod-php5]}
  Line

  #ServiceRestart apache2

  # http://php.net/manual/ru/ini.list.php
  # http://php.net/manual/en/ini.list.php

  # post_max_size=100M
  # upload_max_filesize
  # date.timezone = "Europe/Moscow"
  # session.save_path = "/tmp"
  # short_open_tag
  # expose_php
  # memory_limit
  # user_dir = "www"
  # upload_tmp_dir
  # file_uploads - разрешена закачка файлов или нет

  # Хотите установить пакет для разработчиков PHP5?
  if Confirm "$(gettext "Do you want to install the Developer Tools for PHP5?")" -no; then
    Line
    PackageInstall "php5-dev" -confirm=false ${tested[php5-dev]}
    # Line
    # PackageInstall "phpize" -confirm=true -title="Средство компиляции расширяемых модулей"
  fi

  Line
  Message "$(gettext "Done.")"
}

InstallPHP5