#!/bin/bash

#======================================================================
# Performs installation and configuration of PHP7.
#
# USAGE:
#   php7 [--debug] [--version] [--help] [--nocolor] [--tested]
#
# PROJECT:
#   Hosting tools by Aleksey Nemiro (HTAN)
#
# REQUIREMENTS:
#   Debian 8, sudo
#
# AUTHOR:
#   Aleksey Nemiro
#   http://aleksey.nemiro.ru/
#   https://github.com/alekseynemiro/
#   <aleksey@nemiro.ru>
#   <aleksey.nemiro@gmail.com>
#
# VERSION:
#   1.0.0
#
# CREATED:
#   28.05.2016
#
# REVISION:
#   28.05.2016
#
# COPYRIGHT:
#   © Aleksey Nemiro, 2016. All rights reserved.
#
# LICENSE:
#   Apache License Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0
#
# HTAN_NAME:
#   PHP7 (package)
#
# HTAN_CATEGORY:
#   Application Development
#
# HTAN_OPTIONAL:
#   true
#======================================================================

# Including common
if [[ -z "$HTAN_INCLUDED_TOOLS" ]]; then
  {
    if [[ "${0##*/}" != "php7" ]]; then
      printf "Including the common …"
    fi
    if source "$(cd $(dirname $0) && pwd)/../tools/common"; then
      if [[ "${0##*/}" != "php7" ]]; then
        OK
      fi
    fi
  } || {
    echo ""
    echo -e "\033[1;31m$(gettext "Failed to include the common.")\033[0m"
    exit 1
  }
fi

# Including tools
IncludeTool package service config

InstallPHP7()
{
  # NOTE: it is for the future, when will come the official packages
  if ! $HTAN_NOHEADERS; then
    Line =
    Message "$(gettext "# Installing and configuring %s.")" "PHP5" -s="$DEF_STYLE_HEADER"
    Line =
  fi

  if [[ "$SYS_OS_NAME" == "Ubuntu" ]]; then
    Message "$(gettext "Not available for %s.")" "$SYS_OS_NAME" -s="$DEF_STYLE_ERROR"
    return 1
  fi

  # if PackageInstalled "php5"; then
  #   Message "$(gettext "On this server is already installed %s.")" "PHP5"
  #   Message "$(gettext "Installation of %s is not possible.")." "PHP7"
  #   return
  # fi

  if ! $HTAN_INSTALL_CONFIRMED; then
    if ! Confirm "$(gettext "Do you want to install %s?")" "PHP7" -yes; then
      Line
      Message "$(gettext "Installation canceled by the user.")"
      return
    else
      Line
    fi
  fi

  if PackageInstalled apache2; then
    PackageInstall "php7.0" -confirm=false -title="PHP7"
    Line
    PackageInstall libapache2-mod-php7.0 -confirm=false
    Line
  fi

  PackageInstall php7.0-fpm -confirm=false
  Line

  PackageInstall php7.0-cgi -confirm=false
  Line

  if Confirm "$(gettext "Do you want to install the Developer Tools for %s?")" "PHP7" -no; then
    Line
    PackageInstall "php7.0-dev" -confirm=false
  fi

  # TODO
  # ServerInfo "PHP7:\n"
  # ServerInfo "--------------------------------------------\n"
  # ServerInfo "$(gettext "Location"): $phpPath\n"
  # if PackageInstalled apache2; then
  #   ServerInfo "$(gettext "Config file"): /etc/php7/apache2/php.ini\n"
  # fi
  # ServerInfo "$(gettext "Config file"): /etc/php7/cli/php.ini\n"
  # ServerInfo "$(gettext "Config file"): /etc/php7/fpm/php.ini\n"
  # ServerInfo "$(gettext "Daemon name"): php7.0-fpm\n"
  # ServerInfo "$(gettext "Socket"): /var/run/php7.0-fpm.sock\n"
  # ServerInfo "--------------------------------------------\n\n"

  Line
  Message "$(gettext "Done.")"
}

InstallPHP7