#!/bin/bash

#======================================================================
# Performs installation of sysstat.
#
# USAGE:
#   mc [--debug] [--version] [--help] [--nocolor] [--tested]
#
# PROJECT:
#   Hosting tools by Aleksey Nemiro (HTAN)
#
# REQUIREMENTS:
#   Debian 8, sudo, HTAN Tools
#
# AUTHOR:
#   Aleksey Nemiro
#   http://aleksey.nemiro.ru/
#   https://github.com/alekseynemiro/
#   <aleksey@nemiro.ru>
#   <aleksey.nemiro@gmail.com>
#
# VERSION:
#   1.0.0
#
# CREATED:
#   01.03.2016
#
# REVISION:
#   01.03.2016
#
# COPYRIGHT:
#   © Aleksey Nemiro, 2016. All rights reserved.
#
# LICENSE:
#   Apache License Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0
#
# HTAN_NAME:
#   SYSSTAT
#
# HTAN_CATEGORY:
#   Tools
#
# HTAN_OPTIONAL:
#   true
#======================================================================

# Including common
if [[ -z "$HTAN_INCLUDED_TOOLS" ]]; then
  {
    if [[ "${0##*/}" != "sysstat" ]]; then
      printf "Including the common …"
    fi
    if source "$(cd $(dirname $0) && pwd)/../tools/common"; then
      if [[ "${0##*/}" != "sysstat" ]]; then
        OK
      fi
    fi
  } || {
    echo ""
    echo -e "\033[1;31m$(gettext "Failed to include the common.")\033[0m"
    exit 1
  }
fi

# Including tools
IncludeTool package service

InstallSysStat()
{
  # tested version
  local tested
  if [[ "$HTAN_TESTED" == true ]]; then
    tested="-version=11.0.1"
  fi
  # // --

  Line =
  Message "$(gettext "# Installing %s.")" "SYSSTAT" -s="$DEF_STYLE_HEADER"
  Line =

  Message "$(gettext "The sysstat utilities are a collection of performance monitoring tools.")"
  Line

  PackageInstall sysstat -confirm=true -title="SYSSTAT" $tested

  Line
  Message "$(gettext "Done.")"
}

InstallSysStat