#!/bin/bash

# Including common
if [[ -z $HOSTING_TOOLS_COMMON_FILE_INCLUDED ]]; then
  {
    gettext "Including the common …"; echo -n
    source "$(cd $(dirname $0) && pwd)/../tools/common" && OK
  } || {
    echo ""
    echo -e "\033[1;31mFailed to include the common.\033[0m"
    exit 1
  }
fi

# Including tools
IncludeTool package

InstallUuid()
{
  Line =
  Message "# Установка генератора Universally Unique Identifier." -s="$DEF_STYLE_HEADER"
  Line =

  PackageInstall uuid -confirm=false

  Line
  Message "$(gettext "Done.")"
}

InstallUuid